import type { Driver } from "../types";

export const initialDrivers: Driver[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "+1 (555) 123-4567",
    status: "pending",
    submittedAt: "2024-01-15",
    documents: [
      {
        id: "d1",
        type: "licensefront",
        name: "Driver License Front",
        url: "https://i.ibb.co/TBNLqH11/Rectangle-161124491.png",
        uploadedAt: "2024-01-15",
        status: "pending",
        fileType: "image",
      },
      {
        id: "d2",
        type: "licenseback",
        name: "Driver License Back",
        url: "https://i.ibb.co/HDD0hyY9/Rectangle-161124490.png",
        uploadedAt: "2024-01-15",
        status: "pending",
        fileType: "image",
      },
      {
        id: "d3",
        type: "car",
        name: "Car Front View",
        url: "https://i.ibb.co/99f7Cb01/audi-q5-2019-price-malaysia-2.jpg",
        uploadedAt: "2024-01-15",
        status: "pending",
        fileType: "image",
      },
      {
        id: "d4",
        type: "car",
        name: "Car Back View",
        url: "https://i.ibb.co/6RkshDyc/Rectangle-161124491-2.png",
        uploadedAt: "2024-01-15",
        status: "pending",
        fileType: "image",
      },
      {
        id: "d4a",
        type: "car",
        name: "Car Interior",
        url: "https://i.ibb.co/B2sgrB83/im5.png",
        uploadedAt: "2024-01-15",
        status: "pending",
        fileType: "image",
      },
      {
        id: "d5",
        type: "insurance",
        name: "Insurance Certificate",
        url: "https://example.com/insurance.pdf",
        uploadedAt: "2024-01-15",
        status: "pending",
        fileType: "pdf",
      },
      {
        id: "d6",
        type: "other",
        name: "Interactive License View",
        url: "https://heyzine.com/flip-book/688a6361b7.html",
        uploadedAt: "2024-01-15",
        status: "pending",
        fileType: "link",
      },
    ],
    carModel: "Toyota Camry",
    carYear: 2022,
    licenseNumber: "DL12345678",
  },
  // ... rest of your mock data
];
